travis:
  secure:
    BINSTAR_TOKEN: A89tN5Km3qPvMOIgG7WWEKtJsMTkoetRAht4WkwzPMnLy/v5h4LdBOGbboXgv0DJLuCZWNPLMrFCQ/L9NPUov0BK8sIu5DSRertCjUdlx+WR7VVS55rwHTPI9g21BVyLs5UvsxM1ldXKedeEyF8D0AoxNWAUjwLYU05ngILJHwkhiECV/nCFWfqW2YnUVV3trUJnSiaJN//AkhFU+ocHeF+2/MY5u40ylKCcI1B0O3d5mMjrewApyedJ+GrLUa+RYApjFYHrQRx4Jv9snm3QbaScmEie6tRoO0BJCex0w0QYVRDU7sdWMSRc7aN3Sr2ZaJ4wKPPq7+r8q2SMtDjZxB5oYuhtaT38sf1KnNH7W38t7Z3ZIDP7ti6LaSjWs/rN13LptzY//gCbfYkpWap5FE8r8siFYqWACAC4OSSgEch8xrFim0/NKwk9yAbWNwLT7atokrfj9cS8EaCJL7URHbN5jJLcwtO67K5NqHV2/mbpZPSkRZog2q7YU6fK3hb57Qol6XvLmFebi2KcfJebNvcXsVp/tYOcjM9S5vTxQUT4A277ZPJgUmePfXgCO5YoE2w8A3QcDHvsCilOmQyXYcRWFuHt/cSmGw0IWV2eGV4/GPY36ow1CXVqCgrBcBtc2U4PLJxQAfrSMG4TRrcbBszkGs1NKLyxBLqnZpH4pxg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
