appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: glwPYR/hwwGHJLvD+xKsVNq6iIDW0p6/519Ix2gOnAWHqhk8tqhpB43wToWW1SzFkN793u9ZMu7zcj360SIps66nSK6IRXr9l9zqPKtT30ZoLhj50NXfwAoIsSFKa6YhS62cNFH/cDccz8ZD2+3HUGqRVv3Q55s2O8Gi1N/ORiVxWMDBt2Q+tDcpagK6WI4pQ37n8IdTTdWuY+E2mwxyKISIEB2szIYkzmjKHHfj+KqR97ZS5LRIChbg6ndGQNBZ6BkZ0jyDLvzVS3vqnmV3EnhoWkjwzhSLID+1V+wf2I4FVW8wqz6mqUhKBh9Jtc9gx1tBK1gZ/GWANEaG4KfcKoV44G0F1bHJBlRjo7WZMwN27NBr2h7xMEBIJRFI39UtD3c2PfKgCzL69Q1tGh6lNFBe06N13FtifMrOStsaUHeNzVqo053ZxgRWKqF/fMO41ogw9GljcFl88mzTvh4BOPDBYNztfCIg+pBryyN74eYz3N5yEYRZatIcf2s5J2jrDWoZawLSkzU4/8kpHzI9LnRytN8hQzh3hDUGamuucPY67/PAazAf3LjjVCcrdYj78xJ7fZRSeZJOUZrmUcjsfBLpbg29DzRp24Sl9DEVyHe/msPc4/RjCet6wB0P0M3VGk5Dk0Z4Vnbzc+NfG/BCcCH6XRd+42GndZE6yyPOYNY=}
bot:
  automerge: true
